[project.guitui]
grid = '''
header header header
sidebar content content
sidebar content content
footer footer footer
'''

[project.guitui.processmap]
header=['TEMPLATE_TOP']
sidebar=['cd ~/Desktop','ls -l']
content=['echo "TBD"']
footer=['TEMPLATE_FOOTER']