title = 'Dev [Start Up]'
version = '0.0.1-alpha'
authors = ['dq-mlnck']

[project]
id=['guitui','mock_my_db']

[project.guitui.meta]
name = '(G|T)UI'
version = '0.0.1-alpha'
description = 'Make a Gui using a TUI'
basepath = 'initialize'

[project.mock_my_db.meta]
name = 'Mock My Db'
version = '0.0.1-alpha'
description = 'Database Mocking'
basepath = 'mock-my-db'
