# Sample data for (G|T)UI development
project = "GuiTui Sample"
created = "Date.now()"
version = "0.0.1"

[owner]
"@" = "mlnck"

[[sections]]
id="0"
label='Top Menu'
active=false
fillCharacter='∑'
x=0
y=0
w=100
h=15
scriptSrc='./tm.sh'

[[sections]]
id="1"
label='Left Nav'
active=false
fillCharacter='+'
x=0
y=16 # if number then 16%
w="30" # if string then 30 characters
h=70
scriptSrc='./ln.sh'

[[sections]]
id="2"
label='Footer Data'
active=true
# disabled=true # this key prevents the ability to tab and select the section
fillCharacter='∆'
x=0
y=90
w=100
h=10
scriptSrc='./fc.sh'

[[sections]]
id="3"
label='Main Content'
active=false
fillCharacter='?'
x="31"
y=16
# if width/height omitted then fill remaining space (in phase 2)
## currently, if width/height omitted then throw error
w=[100,"31"] # if array first value should be the largest dimension -> [startValue, ...subtractions]
h=[100,16,11] # would not happenn when using GUI - but shows POC -- remember to add +1 for row which is filled (17-18)
scriptSrc='./main.sh'

[CONFIG]
FILL_CHARACTER = 'z'
RENDER = ['SCROLLABLE_SECTION_WITH_BORDER']
SCRIPT_SOURCE = './global.sh' # this script would set global listeners, etc